test_that("mrema output on test.set", {
  res <- mrema(postdata = test.set$postdata, raw.gs = test.set$gs, DF = 6, threshold = 1.25)
  expect_equal(class(res),  "list")
  expect_equal(class(res[[1]]),  "data.frame")
  expect_equal(class(res[[2]]),  "data.frame")
  expect_equal(nrow(res[[1]]),  1)
  expect_equal(nrow(res[[2]]),  1)
  expect_equal(ncol(res[[1]]),  6)
  expect_equal(ncol(res[[2]]),  18)
  expect_equal(res$results$PVAL,  0.01044263, tolerance = "6e")

  res <- mrema(postdata = test.set$postdata, raw.gs = test.set$gs, DF = 4, threshold = 1.25)
  expect_equal(class(res),  "list")
  expect_equal(class(res[[1]]),  "data.frame")
  expect_equal(class(res[[2]]),  "data.frame")
  expect_equal(nrow(res[[1]]),  1)
  expect_equal(nrow(res[[2]]),  1)
  expect_equal(ncol(res[[1]]),  6)
  expect_equal(ncol(res[[2]]),  18)
  expect_equal(res$results$PVAL,  0.002208153, tolerance = "6e")

  res <- mrema(postdata = test.set$postdata, raw.gs = test.set$gs, DF = 2, threshold = 1.25)
  expect_equal(class(res),  "list")
  expect_equal(class(res[[1]]),  "data.frame")
  expect_equal(class(res[[2]]),  "data.frame")
  expect_equal(nrow(res[[1]]),  1)
  expect_equal(nrow(res[[2]]),  1)
  expect_equal(ncol(res[[1]]),  6)
  expect_equal(ncol(res[[2]]),  18)
  expect_equal(res$results$PVAL,  0.0002362062, tolerance = "6e")

  res <- mrema(postdata = test.set$postdata, raw.gs = test.set$gs, DF = 1, threshold = 1.25)
  expect_equal(class(res),  "list")
  expect_equal(class(res[[1]]),  "data.frame")
  expect_equal(class(res[[2]]),  "data.frame")
  expect_equal(nrow(res[[1]]),  1)
  expect_equal(nrow(res[[2]]),  1)
  expect_equal(ncol(res[[1]]),  6)
  expect_equal(ncol(res[[2]]),  18)
  expect_equal(res$results$PVAL,  4.373173e-05, tolerance = "6e")

})


test_that("mrema error tests", {
  expect_error(mrema(postdata = test.set$postdata, raw.gs = list("smally" = c(paste0("gene.", 1:3))), DF = 6, threshold = 1.25), "No gene sets with more than 5 genes present in data.")
})
